services:

  postgres:

    image: postgres:16

    container_name: auth_postgres

    restart: unless-stopped

    env_file:
      - .env


    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/potgresql/data

volumes:
  postgres_data: